services:
  rolling_gpu:
    build:
      context: .
      dockerfile: docker/Dockerfile.rolling
      args:
        USER: ubuntu
        GROUP: ubuntu
        UID: ${UID}
        GID: ${GID}
        workspace: /home/ubuntu/ros2_ws
    image: "${USER}/ros2log_dev_rolling"
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - __NV_PRIME_RENDER_OFFLOAD=1
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/home/${USER}/.Xauthority:/home/ubuntu/.Xauthority"
      - "/home/${USER}/.gazebo:/home/ubuntu/.gazebo"
      - "/home/${USER}/.ros:/home/ubuntu/.ros"
      - "${PWD}/docker/initial_setting.sh:/initial_setting.sh"
      - "${PWD}/docker/ros2_ws:/home/ubuntu/ros2_ws/"
      - "${PWD}/ros2cli:/home/ubuntu/ros2_ws/src/ros2cli"
      - "/etc/localtime:/etc/localtime:ro"
      - "/media:/media"
      - "/dev:/dev"
      - "/lib/modules:/lib/modules:ro"
      - "/etc/udev:/etc/udev:ro"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
  rolling_cpu:
    build:
      context: .
      dockerfile: docker/Dockerfile.rolling
      args:
        USER: ubuntu
        GROUP: ubuntu
        UID: ${UID}
        GID: ${GID}
        workspace: /home/ubuntu/ros2_ws
    image: "${USER}/ros2log_dev_rolling"
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/home/${USER}/.Xauthority:/home/ubuntu/.Xauthority"
      - "/home/${USER}/.gazebo:/home/ubuntu/.gazebo"
      - "/home/${USER}/.ros:/home/ubuntu/.ros"
      - "${PWD}/docker/initial_setting.sh:/initial_setting.sh"
      - "${PWD}/docker/ros2_ws:/home/ubuntu/ros2_ws/"
      - "${PWD}/ros2cli:/home/ubuntu/ros2_ws/src/ros2cli"
      - "/etc/localtime:/etc/localtime:ro"
      - "/media:/media"
      - "/dev:/dev"
      - "/lib/modules:/lib/modules:ro"
      - "/etc/udev:/etc/udev:ro"
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
